services:
  - type: web
    name: coswo-backend
    env: node
    plan: free
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: MONGO_URI
        sync: false
    autoDeploy: false
